# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{watirsplash}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jarmo Pertman"]
  s.date = %q{2011-01-26}
  s.default_executable = %q{watirsplash}
  s.description = %q{WatirSplash makes testing of web applications splashin' easy by combining best features of Watir, RSpec and Ruby!}
  s.email = %q{jarmo.p@gmail.com}
  s.executables = ["watirsplash"]
  s.extra_rdoc_files = [
    "History.rdoc",
     "License.txt",
     "README.rdoc"
  ]
  s.files = [
    "History.rdoc",
     "License.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/watirsplash",
     "lib/watirsplash.rb",
     "lib/watirsplash/cli.rb",
     "lib/watirsplash/file_helper.rb",
     "lib/watirsplash/generators/migrate_project.rb",
     "lib/watirsplash/generators/new_common_project.rb",
     "lib/watirsplash/generators/new_project.rb",
     "lib/watirsplash/generators/templates/new_common_project/config.rb.tt",
     "lib/watirsplash/generators/templates/new_common_project/environment.rb",
     "lib/watirsplash/generators/templates/new_common_project/lib/common_application_helper.rb",
     "lib/watirsplash/generators/templates/new_project/.rspec",
     "lib/watirsplash/generators/templates/new_project/config.rb.tt",
     "lib/watirsplash/generators/templates/new_project/environment.rb.tt",
     "lib/watirsplash/generators/templates/new_project/spec/%formatted_name%_helper.rb.tt",
     "lib/watirsplash/generators/templates/new_project/spec/dummy_spec.rb.tt",
     "lib/watirsplash/html_formatter.rb",
     "lib/watirsplash/rspec_patches.rb",
     "lib/watirsplash/spec_helper.rb",
     "lib/watirsplash/util.rb",
     "lib/watirsplash/watir_patches.rb",
     "spec/file_helper_spec.rb",
     "spec/spec_helper_spec.rb",
     "spec/spec_match_array_spec.rb",
     "spec/util_spec.rb",
     "spec/watir_ie_spec.rb"
  ]
  s.homepage = %q{http://github.com/jarmo/WatirSplash}
  s.post_install_message = %q{*************************

Thank you for installing WatirSplash 1.0.0! Don't forget to take a look at the README and History files!

Execute `watirsplash new` under your project's directory to generate default project structure.

PS! If you are using older WatirSplash version <= 0.2.14, then execute `watirsplash migrate` under ui-test and ui-test-common!

*************************}
  s.rdoc_options = ["--charset=UTF-8", "--main", "README.rdoc", "--template", "hanna", "--inline-source", "--format=html"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{watirsplash 1.0.0}
  s.test_files = [
    "spec/file_helper_spec.rb",
     "spec/spec_helper_spec.rb",
     "spec/spec_match_array_spec.rb",
     "spec/util_spec.rb",
     "spec/watir_ie_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<watir>, ["= 1.7.1"])
      s.add_runtime_dependency(%q<rspec>, ["~> 2.4"])
      s.add_runtime_dependency(%q<require_all>, [">= 0"])
      s.add_runtime_dependency(%q<syntax>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, ["~> 0"])
      s.add_runtime_dependency(%q<rautomation>, ["~> 0.4"])
      s.add_runtime_dependency(%q<require_all>, [">= 0"])
      s.add_runtime_dependency(%q<syntax>, [">= 0"])
      s.add_runtime_dependency(%q<win32screenshot>, ["~> 1.0.2"])
    else
      s.add_dependency(%q<watir>, ["= 1.7.1"])
      s.add_dependency(%q<rspec>, ["~> 2.4"])
      s.add_dependency(%q<require_all>, [">= 0"])
      s.add_dependency(%q<syntax>, [">= 0"])
      s.add_dependency(%q<thor>, ["~> 0"])
      s.add_dependency(%q<rautomation>, ["~> 0.4"])
      s.add_dependency(%q<require_all>, [">= 0"])
      s.add_dependency(%q<syntax>, [">= 0"])
      s.add_dependency(%q<win32screenshot>, ["~> 1.0.2"])
    end
  else
    s.add_dependency(%q<watir>, ["= 1.7.1"])
    s.add_dependency(%q<rspec>, ["~> 2.4"])
    s.add_dependency(%q<require_all>, [">= 0"])
    s.add_dependency(%q<syntax>, [">= 0"])
    s.add_dependency(%q<thor>, ["~> 0"])
    s.add_dependency(%q<rautomation>, ["~> 0.4"])
    s.add_dependency(%q<require_all>, [">= 0"])
    s.add_dependency(%q<syntax>, [">= 0"])
    s.add_dependency(%q<win32screenshot>, ["~> 1.0.2"])
  end
end

